// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * M​u​ ​S​t​r​e​a​m
	 */
	title: string
	waitingScreen: {
		/**
		 * S​h​a​r​e​ ​i​n​t​e​n​s​e​ ​l​i​s​t​e​n​i​n​g​ ​s​e​s​s​i​o​n​s​ ​w​i​t​h​ ​y​o​u​r​ ​f​r​i​e​n​d​s​!
		 */
		slogan: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​R​o​o​m
		 */
		createRoomBtn: string
		/**
		 * J​o​i​n​ ​a​ ​R​o​o​m
		 */
		joinRoomBtn: string
		/**
		 * O​R
		 */
		roomChoiceSeparator: string
		/**
		 * R​o​o​m​ ​C​o​d​e
		 */
		roomCodeInput: string
	}
	joinRoomPopup: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		userName: string
		/**
		 * R​o​o​m​ ​C​o​d​e
		 */
		roomCodeInput: string
		/**
		 * J​o​i​n
		 */
		joinBtn: string
	}
	waitingScreenTutorial: {
		stepWelcome: {
			/**
			 * W​e​l​c​o​m​e​ ​t​o​ ​M​u​ ​S​t​r​e​a​m
			 */
			title: string
			/**
			 * M​u​ ​S​t​r​e​a​m​ ​i​s​ ​a​n​ ​a​p​p​ ​t​h​a​t​ ​l​e​t​s​ ​y​o​u​ ​s​h​a​r​e​ ​l​i​s​t​e​n​i​n​g​ ​s​e​s​s​i​o​n​s​ ​w​i​t​h​ ​y​o​u​r​ ​f​r​i​e​n​d​s​.​ ​H​e​r​e​’​s​ ​a​ ​t​u​t​o​r​i​a​l​ ​t​o​ ​h​e​l​p​ ​y​o​u​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			description: string
		}
		stepCreateRoom: {
			/**
			 * C​r​e​a​t​e​ ​a​ ​R​o​o​m
			 */
			title: string
			/**
			 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​r​o​o​m​.​ ​A​ ​c​o​d​e​ ​w​i​l​l​ ​b​e​ ​g​e​n​e​r​a​t​e​d​,​ ​a​n​d​ ​y​o​u​ ​c​a​n​ ​c​o​p​y​ ​a​n​d​ ​s​h​a​r​e​ ​i​t​ ​w​i​t​h​ ​y​o​u​r​ ​f​r​i​e​n​d​s​ ​s​o​ ​t​h​e​y​ ​c​a​n​ ​j​o​i​n​ ​y​o​u​.
			 */
			description: string
		}
		stepJoinRoom: {
			/**
			 * J​o​i​n​ ​a​ ​R​o​o​m
			 */
			title: string
			/**
			 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​r​o​o​m​.​ ​A​ ​r​o​o​m​ ​c​o​d​e​ ​w​i​l​l​ ​b​e​ ​g​e​n​e​r​a​t​e​d​,​ ​a​n​d​ ​y​o​u​ ​c​a​n​ ​c​o​p​y​ ​a​n​d​ ​s​h​a​r​e​ ​i​t​ ​w​i​t​h​ ​y​o​u​r​ ​f​r​i​e​n​d​s​ ​s​o​ ​t​h​e​y​ ​c​a​n​ ​j​o​i​n​ ​y​o​u​.
			 */
			description: string
			/**
			 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​j​o​i​n​ ​a​ ​r​o​o​m​.
			 */
			description1: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​u​s​e​r​n​a​m​e​ ​h​e​r​e​.
			 */
			description2: string
			/**
			 * E​n​t​e​r​ ​t​h​e​ ​r​o​o​m​ ​c​o​d​e​ ​h​e​r​e​.
			 */
			description3: string
			/**
			 * A​n​d​ ​y​o​u​’​r​e​ ​g​o​o​d​ ​t​o​ ​g​o​!
			 */
			description4: string
		}
	}
	roomScreen: {
		/**
		 * C​o​d​e
		 */
		code: string
		/**
		 * D​e​l​e​t​e​ ​R​o​o​m
		 */
		deleteRoom: string
		/**
		 * L​o​g​ ​O​u​t
		 */
		deconexion: string
		/**
		 * P​a​r​t​i​c​i​p​a​n​t​s
		 */
		participants: string
		/**
		 * P​l​a​y​l​i​s​t
		 */
		playlist: string
		/**
		 * L​i​v​e​ ​C​h​a​t
		 */
		chat: string
		/**
		 * R​e​a​c​t
		 */
		react: string
	}
	warningPopup: {
		/**
		 * M​u​ ​S​t​r​e​a​m​ ​i​s​ ​n​o​t​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​t​h​e​ ​a​u​d​i​o​ ​c​o​n​t​e​n​t​ ​s​h​a​r​e​d​ ​b​y​ ​p​a​r​t​i​c​i​p​a​n​t​s​.​ ​Y​o​u​ ​a​r​e​ ​s​o​l​e​l​y​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​i​t​.
		 */
		descritption: string
		/**
		 * D​o​ ​n​o​t​ ​s​h​o​w​ ​a​g​a​i​n
		 */
		quit: string
	}
	roomScreenTutorial: {
		stepWelcome: {
			/**
			 * W​e​l​c​o​m​e​ ​t​o​ ​t​h​e​ ​R​o​o​m
			 */
			title: string
			/**
			 * Y​o​u​’​r​e​ ​i​n​ ​a​ ​p​r​i​v​a​t​e​ ​m​u​s​i​c​ ​l​i​s​t​e​n​i​n​g​ ​r​o​o​m​.​ ​H​e​r​e​’​s​ ​a​ ​t​u​t​o​r​i​a​l​ ​t​o​ ​h​e​l​p​ ​y​o​u​ ​n​a​v​i​g​a​t​e​.
			 */
			description: string
		}
		stepCode: {
			/**
			 * R​o​o​m​ ​C​o​d​e
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​s​h​a​r​e​ ​t​h​i​s​ ​c​o​d​e​ ​w​i​t​h​ ​y​o​u​r​ ​f​r​i​e​n​d​s​ ​s​o​ ​t​h​e​y​ ​c​a​n​ ​j​o​i​n​ ​y​o​u​r​ ​r​o​o​m​.​ ​T​h​e​ ​e​y​e​ ​i​c​o​n​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​v​i​e​w​ ​i​t​,​ ​a​n​d​ ​t​h​e​ ​c​o​p​y​ ​i​c​o​n​ ​l​e​t​s​ ​y​o​u​ ​c​o​p​y​ ​i​t​ ​d​i​r​e​c​t​l​y​ ​t​o​ ​y​o​u​r​ ​c​l​i​p​b​o​a​r​d​.
			 */
			description: string
		}
		stepAddSong: {
			/**
			 * A​d​d​ ​a​ ​S​o​n​g
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​a​d​d​ ​a​ ​s​o​n​g​ ​t​o​ ​t​h​e​ ​r​o​o​m​ ​b​y​ ​p​r​e​s​s​i​n​g​ ​h​e​r​e​.
			 */
			description: string
		}
		stepReact: {
			/**
			 * A​d​d​ ​a​ ​R​e​a​c​t​i​o​n
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​r​e​a​c​t​ ​t​o​ ​t​h​e​ ​m​u​s​i​c​!
			 */
			description: string
		}
		stepMusicControl: {
			/**
			 * M​u​s​i​c​ ​C​o​n​t​r​o​l​s
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​c​o​n​t​r​o​l​ ​t​h​e​ ​m​u​s​i​c​ ​u​s​i​n​g​ ​t​h​e​ ​b​u​t​t​o​n​s​ ​h​e​r​e​.
			 */
			description: string
		}
		stepQuitRoom: {
			/**
			 * L​e​a​v​e​ ​t​h​e​ ​R​o​o​m
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​l​e​a​v​e​ ​o​r​ ​d​i​s​s​o​l​v​e​ ​t​h​e​ ​r​o​o​m​ ​b​y​ ​c​l​i​c​k​i​n​g​ ​h​e​r​e​.
			 */
			description: string
		}
		stepFinal: {
			/**
			 * H​a​v​e​ ​F​u​n​!
			 */
			title: string
			/**
			 * T​h​a​t​’​s​ ​i​t​,​ ​y​o​u​ ​k​n​o​w​ ​e​v​e​r​y​t​h​i​n​g​,​ ​y​o​u​’​r​e​ ​r​e​a​d​y​ ​t​o​ ​f​u​l​l​y​ ​e​n​j​o​y​ ​M​u​ ​S​t​r​e​a​m​.
			 */
			description: string
		}
	}
	common: {
		/**
		 * S​t​e​p​ ​{​c​u​r​r​e​n​t​}​ ​o​f​ ​{​t​o​t​a​l​}
		 * @param {string} current
		 * @param {string} total
		 */
		tutorialStep: RequiredParams<'current' | 'total'>
	}
	alertToast: {
		/**
		 * {​n​a​m​e​}​ ​h​a​s​ ​j​o​i​n​e​d​ ​t​h​e​ ​r​o​o​m
		 * @param {string} name
		 */
		newParticipant: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​h​a​s​ ​l​e​f​t​ ​t​h​e​ ​r​o​o​m
		 * @param {string} name
		 */
		participantLeft: RequiredParams<'name'>
		/**
		 * C​o​d​e​ ​c​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copiedRoomCode: string
	}
	settingsPopup: {
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
	}
}

export type TranslationFunctions = {
	/**
	 * Mu Stream
	 */
	title: () => LocalizedString
	waitingScreen: {
		/**
		 * Share intense listening sessions with your friends!
		 */
		slogan: () => LocalizedString
		/**
		 * Create a Room
		 */
		createRoomBtn: () => LocalizedString
		/**
		 * Join a Room
		 */
		joinRoomBtn: () => LocalizedString
		/**
		 * OR
		 */
		roomChoiceSeparator: () => LocalizedString
		/**
		 * Room Code
		 */
		roomCodeInput: () => LocalizedString
	}
	joinRoomPopup: {
		/**
		 * Username
		 */
		userName: () => LocalizedString
		/**
		 * Room Code
		 */
		roomCodeInput: () => LocalizedString
		/**
		 * Join
		 */
		joinBtn: () => LocalizedString
	}
	waitingScreenTutorial: {
		stepWelcome: {
			/**
			 * Welcome to Mu Stream
			 */
			title: () => LocalizedString
			/**
			 * Mu Stream is an app that lets you share listening sessions with your friends. Here’s a tutorial to help you get started.
			 */
			description: () => LocalizedString
		}
		stepCreateRoom: {
			/**
			 * Create a Room
			 */
			title: () => LocalizedString
			/**
			 * Click here to create a room. A code will be generated, and you can copy and share it with your friends so they can join you.
			 */
			description: () => LocalizedString
		}
		stepJoinRoom: {
			/**
			 * Join a Room
			 */
			title: () => LocalizedString
			/**
			 * Click here to create a room. A room code will be generated, and you can copy and share it with your friends so they can join you.
			 */
			description: () => LocalizedString
			/**
			 * Click here to join a room.
			 */
			description1: () => LocalizedString
			/**
			 * Enter your username here.
			 */
			description2: () => LocalizedString
			/**
			 * Enter the room code here.
			 */
			description3: () => LocalizedString
			/**
			 * And you’re good to go!
			 */
			description4: () => LocalizedString
		}
	}
	roomScreen: {
		/**
		 * Code
		 */
		code: () => LocalizedString
		/**
		 * Delete Room
		 */
		deleteRoom: () => LocalizedString
		/**
		 * Log Out
		 */
		deconexion: () => LocalizedString
		/**
		 * Participants
		 */
		participants: () => LocalizedString
		/**
		 * Playlist
		 */
		playlist: () => LocalizedString
		/**
		 * Live Chat
		 */
		chat: () => LocalizedString
		/**
		 * React
		 */
		react: () => LocalizedString
	}
	warningPopup: {
		/**
		 * Mu Stream is not responsible for the audio content shared by participants. You are solely responsible for it.
		 */
		descritption: () => LocalizedString
		/**
		 * Do not show again
		 */
		quit: () => LocalizedString
	}
	roomScreenTutorial: {
		stepWelcome: {
			/**
			 * Welcome to the Room
			 */
			title: () => LocalizedString
			/**
			 * You’re in a private music listening room. Here’s a tutorial to help you navigate.
			 */
			description: () => LocalizedString
		}
		stepCode: {
			/**
			 * Room Code
			 */
			title: () => LocalizedString
			/**
			 * You can share this code with your friends so they can join your room. The eye icon allows you to view it, and the copy icon lets you copy it directly to your clipboard.
			 */
			description: () => LocalizedString
		}
		stepAddSong: {
			/**
			 * Add a Song
			 */
			title: () => LocalizedString
			/**
			 * You can add a song to the room by pressing here.
			 */
			description: () => LocalizedString
		}
		stepReact: {
			/**
			 * Add a Reaction
			 */
			title: () => LocalizedString
			/**
			 * You can react to the music!
			 */
			description: () => LocalizedString
		}
		stepMusicControl: {
			/**
			 * Music Controls
			 */
			title: () => LocalizedString
			/**
			 * You can control the music using the buttons here.
			 */
			description: () => LocalizedString
		}
		stepQuitRoom: {
			/**
			 * Leave the Room
			 */
			title: () => LocalizedString
			/**
			 * You can leave or dissolve the room by clicking here.
			 */
			description: () => LocalizedString
		}
		stepFinal: {
			/**
			 * Have Fun!
			 */
			title: () => LocalizedString
			/**
			 * That’s it, you know everything, you’re ready to fully enjoy Mu Stream.
			 */
			description: () => LocalizedString
		}
	}
	common: {
		/**
		 * Step {current} of {total}
		 */
		tutorialStep: (arg: { current: string, total: string }) => LocalizedString
	}
	alertToast: {
		/**
		 * {name} has joined the room
		 */
		newParticipant: (arg: { name: string }) => LocalizedString
		/**
		 * {name} has left the room
		 */
		participantLeft: (arg: { name: string }) => LocalizedString
		/**
		 * Code copied to clipboard
		 */
		copiedRoomCode: () => LocalizedString
	}
	settingsPopup: {
		/**
		 * Language
		 */
		language: () => LocalizedString
	}
}

export type Formatters = {}
