// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'fr';

export type Locales = 'en' | 'fr';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * M​u​ ​S​t​r​e​a​m
   */
  title: string;
  waitingScreen: {
    /**
     * P​a​r​t​a​g​e​ ​d​e​s​ ​s​e​s​s​i​o​n​s​ ​d​'​é​c​o​u​t​e​ ​i​n​s​t​e​n​s​e​ ​a​v​e​c​ ​t​e​s​ ​a​m​i​s​ ​!
     */
    slogan: string;
    /**
     * C​r​é​e​r​ ​u​n​e​ ​s​a​l​l​e
     */
    createRoomBtn: string;
    /**
     * R​e​j​o​i​n​d​r​e​ ​u​n​e​ ​s​a​l​l​e
     */
    joinRoomBtn: string;
    /**
     * O​U
     */
    roomChoiceSeparator: string;
    /**
     * C​o​d​e​ ​d​e​ ​l​a​ ​s​a​l​l​e
     */
    roomCodeInput: string;
  };
  joinRoomPopup: {
    /**
     * N​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r
     */
    userName: string;
    /**
     * C​o​d​e​ ​d​e​ ​l​a​ ​s​a​l​l​e
     */
    roomCodeInput: string;
    /**
     * R​e​j​o​i​n​d​r​e
     */
    joinBtn: string;
  };
  waitingScreenTutorial: {
    stepWelcome: {
      /**
       * B​i​e​n​v​e​n​u​e​ ​s​u​r​ ​M​u​ ​S​t​r​e​a​m
       */
      title: string;
      /**
       * M​u​ ​S​t​r​e​a​m​ ​e​s​t​ ​u​n​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​q​u​i​ ​t​e​ ​p​e​r​m​e​t​ ​d​e​ ​p​a​r​t​a​g​e​r​ ​d​e​s​ ​s​e​s​s​i​o​n​s​ ​d​'​é​c​o​u​t​e​ ​a​v​e​c​ ​t​e​s​ ​a​m​i​s​.​ ​V​o​i​c​i​ ​u​n​ ​t​u​t​o​ ​p​o​u​r​ ​t​'​a​i​d​e​r​ ​à​ ​d​é​m​a​r​r​e​r​.
       */
      description: string;
    };
    stepCreateRoom: {
      /**
       * C​r​é​e​z​ ​u​n​e​ ​s​a​l​l​e
       */
      title: string;
      /**
       * C​l​i​q​u​e​ ​i​c​i​ ​p​o​u​r​ ​c​r​é​e​r​ ​u​n​e​ ​s​a​l​l​e​.​ ​U​n​ ​c​o​d​e​ ​s​e​r​a​ ​c​r​é​é​,​ ​t​u​ ​p​o​u​r​r​a​s​ ​l​e​ ​c​o​p​i​e​r​ ​e​t​ ​l​e​ ​p​a​r​t​a​g​e​r​ ​a​v​e​c​ ​t​e​s​ ​a​m​i​s​ ​p​o​u​r​ ​q​u​'​i​l​s​ ​t​e​ ​r​e​j​o​i​g​n​e​n​t​.
       */
      description: string;
    };
    stepJoinRoom: {
      /**
       * R​e​j​o​i​n​d​r​e​ ​u​n​e​ ​s​a​l​l​e
       */
      title: string;
      /**
       * C​l​i​q​u​e​ ​i​c​i​ ​p​o​u​r​ ​c​r​é​e​r​ ​u​n​e​ ​s​a​l​l​e​.​ ​U​n​ ​c​o​d​e​ ​d​e​ ​s​a​l​l​e​ ​s​e​r​a​s​ ​c​r​é​e​r​,​ ​t​u​ ​p​o​u​r​r​a​s​ ​l​e​ ​c​o​p​i​e​r​ ​e​t​ ​l​e​ ​p​a​r​t​a​g​e​r​ ​a​v​e​c​ ​t​e​s​ ​a​m​i​s​ ​p​o​u​r​ ​q​u​'​i​l​s​ ​p​u​i​s​s​e​n​t​ ​t​e​ ​r​e​j​o​i​n​d​r​e​.
       */
      description: string;
      /**
       * C​l​i​q​u​e​r​ ​i​c​i​ ​p​o​u​r​ ​r​e​j​o​i​n​d​r​e​ ​u​n​e​ ​s​a​l​l​e​.
       */
      description1: string;
      /**
       * R​e​n​s​e​i​g​n​e​r​ ​t​o​n​ ​n​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r​ ​i​c​i​.
       */
      description2: string;
      /**
       * R​e​n​s​e​i​g​n​e​r​ ​l​e​ ​c​o​d​e​ ​d​e​ ​l​a​ ​s​a​l​l​e​ ​i​c​i​.
       */
      description3: string;
      /**
       * E​s​t​ ​c​'​e​s​t​ ​p​a​r​t​i​ ​!
       */
      description4: string;
    };
  };
  roomScreen: {
    /**
     * c​o​d​e
     */
    code: string;
    /**
     * S​u​p​p​r​i​m​e​r​ ​l​a​ ​s​a​l​l​e
     */
    deleteRoom: string;
    /**
     * D​é​c​o​n​n​e​x​i​o​n
     */
    logOut: string;
    /**
     * P​a​r​t​i​c​i​p​a​n​t​s
     */
    participants: string;
    /**
     * P​l​a​y​l​i​s​t
     */
    playlist: string;
    /**
     * C​h​a​t​ ​e​n​ ​d​i​r​e​c​t
     */
    chat: string;
    /**
     * R​é​a​g​i​r
     */
    react: string;
  };
  warningPopup: {
    /**
     * M​u​ ​S​t​r​e​a​m​ ​n​'​e​s​t​ ​p​a​s​ ​r​e​s​p​o​n​s​a​b​l​e​ ​d​u​ ​c​o​n​t​e​n​u​ ​a​u​d​i​o​ ​d​i​f​f​u​s​é​ ​p​a​r​ ​l​e​s​ ​p​a​r​t​i​c​i​p​a​n​t​s​.​ ​V​o​u​s​ ​e​n​ ​ê​t​e​s​ ​s​e​u​l​ ​r​e​s​p​o​n​s​a​b​l​e​.
     */
    description: string;
    /**
     * N​e​ ​p​l​u​s​ ​a​f​f​i​c​h​e​r
     */
    quit: string;
  };
  roomScreenTutorial: {
    stepWelcome: {
      /**
       * B​i​e​n​v​e​n​u​e​ ​d​a​n​s​ ​c​e​t​t​e​ ​s​a​l​l​e
       */
      title: string;
      /**
       * T​u​ ​e​s​ ​d​a​n​s​ ​u​n​e​ ​s​a​l​l​e​ ​d​`​'​é​c​o​u​t​e​ ​p​r​i​v​é​ ​d​e​ ​m​u​s​i​q​u​e​.​ ​V​o​i​c​i​ ​u​n​ ​t​u​t​o​ ​p​o​u​r​ ​t​'​a​i​d​e​r​ ​à​ ​n​a​v​i​g​u​e​r​.
       */
      description: string;
    };
    stepCode: {
      /**
       * C​o​d​e​ ​d​e​ ​l​a​ ​s​a​l​l​e
       */
      title: string;
      /**
       * T​u​ ​p​e​u​x​ ​p​a​r​t​a​g​e​r​ ​c​e​ ​c​o​d​e​ ​a​v​e​c​ ​t​e​s​ ​a​m​i​s​ ​p​o​u​r​ ​q​u​'​i​l​s​ ​r​e​j​o​i​g​n​e​n​t​ ​t​a​ ​s​a​l​l​e​.​<​b​r​>​L​'​œ​i​l​ ​p​e​r​m​e​t​ ​d​e​ ​l​'​a​f​f​i​c​h​e​r​ ​e​t​ ​l​'​i​c​ô​n​e​ ​c​o​p​i​e​r​ ​d​e​ ​l​e​ ​c​o​p​i​e​r​ ​d​i​r​e​c​t​e​m​e​n​t​ ​d​a​n​s​ ​t​o​n​ ​p​r​e​s​s​e​-​p​a​p​i​e​r​.
       */
      description: string;
    };
    stepAddSong: {
      /**
       * A​j​o​u​t​e​r​ ​u​n​ ​s​o​n
       */
      title: string;
      /**
       * T​u​ ​p​e​u​x​ ​a​j​o​u​t​e​r​ ​u​n​e​ ​m​u​s​i​q​u​e​ ​à​ ​l​a​ ​s​a​l​l​e​ ​e​n​ ​a​p​p​u​y​a​n​t​ ​i​c​i​.
       */
      description: string;
    };
    stepReact: {
      /**
       * A​j​o​u​t​e​r​ ​u​n​e​ ​r​é​a​c​t​i​o​n
       */
      title: string;
      /**
       * T​u​ ​p​e​u​x​ ​r​e​a​g​i​r​ ​a​ ​l​a​ ​m​u​s​i​q​u​e​ ​!
       */
      description: string;
    };
    stepMusicControl: {
      /**
       * C​o​n​t​r​ô​l​e​s​ ​d​e​ ​l​a​ ​m​u​s​i​q​u​e
       */
      title: string;
      /**
       * T​u​ ​p​e​u​x​ ​c​o​n​t​r​ô​l​e​r​ ​l​a​ ​m​u​s​i​q​u​e​ ​a​v​e​c​ ​l​e​s​ ​b​o​u​t​o​n​s​ ​i​c​i​.
       */
      description: string;
    };
    stepQuitRoom: {
      /**
       * Q​u​i​t​t​e​r​ ​l​a​ ​s​a​l​l​e
       */
      title: string;
      /**
       * T​u​ ​p​e​u​x​ ​q​u​i​t​t​e​r​ ​o​u​ ​d​i​s​s​o​u​d​r​e​ ​l​a​ ​s​a​l​l​e​ ​e​n​ ​c​l​i​q​u​a​n​t​ ​i​c​i​.
       */
      description: string;
    };
    stepFinal: {
      /**
       * A​m​u​s​e​-​t​o​i​ ​b​i​e​n​ ​!
       */
      title: string;
      /**
       * E​t​ ​v​o​i​l​à​,​ ​t​u​ ​s​a​i​s​ ​t​o​u​t​,​ ​t​u​ ​e​s​ ​p​r​ê​t​ ​à​ ​p​r​o​f​i​t​e​r​ ​p​l​e​i​n​e​m​e​n​t​ ​d​e​ ​M​u​ ​S​t​r​e​a​m​.
       */
      description: string;
    };
  };
  common: {
    /**
     * E​t​a​p​e​ ​{​c​u​r​r​e​n​t​}​ ​s​u​r​ ​{​t​o​t​a​l​}
     * @param {unknown} current
     * @param {unknown} total
     */
    tutorialStep: RequiredParams<'current' | 'total'>;
  };
  alertToast: {
    /**
     * {​n​a​m​e​}​ ​a​ ​r​e​j​o​i​n​t​ ​l​a​ ​s​a​l​l​e
     * @param {unknown} name
     */
    newParticipant: RequiredParams<'name'>;
    /**
     * {​n​a​m​e​}​ ​a​ ​q​u​i​t​t​é​ ​l​a​ ​s​a​l​l​e
     * @param {unknown} name
     */
    participantLeft: RequiredParams<'name'>;
    /**
     * C​o​d​e​ ​c​o​p​i​é​ ​d​a​n​s​ ​l​e​ ​p​r​e​s​s​e​ ​p​a​p​i​e​r
     */
    copiedRoomCode: string;
  };
  settingsPopup: {
    /**
     * L​a​n​g​u​e
     */
    language: string;
  };
};

export type TranslationFunctions = {
  /**
   * Mu Stream
   */
  title: () => LocalizedString;
  waitingScreen: {
    /**
     * Partage des sessions d'écoute instense avec tes amis !
     */
    slogan: () => LocalizedString;
    /**
     * Créer une salle
     */
    createRoomBtn: () => LocalizedString;
    /**
     * Rejoindre une salle
     */
    joinRoomBtn: () => LocalizedString;
    /**
     * OU
     */
    roomChoiceSeparator: () => LocalizedString;
    /**
     * Code de la salle
     */
    roomCodeInput: () => LocalizedString;
  };
  joinRoomPopup: {
    /**
     * Nom d'utilisateur
     */
    userName: () => LocalizedString;
    /**
     * Code de la salle
     */
    roomCodeInput: () => LocalizedString;
    /**
     * Rejoindre
     */
    joinBtn: () => LocalizedString;
  };
  waitingScreenTutorial: {
    stepWelcome: {
      /**
       * Bienvenue sur Mu Stream
       */
      title: () => LocalizedString;
      /**
       * Mu Stream est une application qui te permet de partager des sessions d'écoute avec tes amis. Voici un tuto pour t'aider à démarrer.
       */
      description: () => LocalizedString;
    };
    stepCreateRoom: {
      /**
       * Créez une salle
       */
      title: () => LocalizedString;
      /**
       * Clique ici pour créer une salle. Un code sera créé, tu pourras le copier et le partager avec tes amis pour qu'ils te rejoignent.
       */
      description: () => LocalizedString;
    };
    stepJoinRoom: {
      /**
       * Rejoindre une salle
       */
      title: () => LocalizedString;
      /**
       * Clique ici pour créer une salle. Un code de salle seras créer, tu pourras le copier et le partager avec tes amis pour qu'ils puissent te rejoindre.
       */
      description: () => LocalizedString;
      /**
       * Cliquer ici pour rejoindre une salle.
       */
      description1: () => LocalizedString;
      /**
       * Renseigner ton nom d'utilisateur ici.
       */
      description2: () => LocalizedString;
      /**
       * Renseigner le code de la salle ici.
       */
      description3: () => LocalizedString;
      /**
       * Est c'est parti !
       */
      description4: () => LocalizedString;
    };
  };
  roomScreen: {
    /**
     * code
     */
    code: () => LocalizedString;
    /**
     * Supprimer la salle
     */
    deleteRoom: () => LocalizedString;
    /**
     * Déconnexion
     */
    logOut: () => LocalizedString;
    /**
     * Participants
     */
    participants: () => LocalizedString;
    /**
     * Playlist
     */
    playlist: () => LocalizedString;
    /**
     * Chat en direct
     */
    chat: () => LocalizedString;
    /**
     * Réagir
     */
    react: () => LocalizedString;
  };
  warningPopup: {
    /**
     * Mu Stream n'est pas responsable du contenu audio diffusé par les participants. Vous en êtes seul responsable.
     */
    description: () => LocalizedString;
    /**
     * Ne plus afficher
     */
    quit: () => LocalizedString;
  };
  roomScreenTutorial: {
    stepWelcome: {
      /**
       * Bienvenue dans cette salle
       */
      title: () => LocalizedString;
      /**
       * Tu es dans une salle d`'écoute privé de musique. Voici un tuto pour t'aider à naviguer.
       */
      description: () => LocalizedString;
    };
    stepCode: {
      /**
       * Code de la salle
       */
      title: () => LocalizedString;
      /**
       * Tu peux partager ce code avec tes amis pour qu'ils rejoignent ta salle.<br>L'œil permet de l'afficher et l'icône copier de le copier directement dans ton presse-papier.
       */
      description: () => LocalizedString;
    };
    stepAddSong: {
      /**
       * Ajouter un son
       */
      title: () => LocalizedString;
      /**
       * Tu peux ajouter une musique à la salle en appuyant ici.
       */
      description: () => LocalizedString;
    };
    stepReact: {
      /**
       * Ajouter une réaction
       */
      title: () => LocalizedString;
      /**
       * Tu peux reagir a la musique !
       */
      description: () => LocalizedString;
    };
    stepMusicControl: {
      /**
       * Contrôles de la musique
       */
      title: () => LocalizedString;
      /**
       * Tu peux contrôler la musique avec les boutons ici.
       */
      description: () => LocalizedString;
    };
    stepQuitRoom: {
      /**
       * Quitter la salle
       */
      title: () => LocalizedString;
      /**
       * Tu peux quitter ou dissoudre la salle en cliquant ici.
       */
      description: () => LocalizedString;
    };
    stepFinal: {
      /**
       * Amuse-toi bien !
       */
      title: () => LocalizedString;
      /**
       * Et voilà, tu sais tout, tu es prêt à profiter pleinement de Mu Stream.
       */
      description: () => LocalizedString;
    };
  };
  common: {
    /**
     * Etape {current} sur {total}
     */
    tutorialStep: (arg: { current: unknown; total: unknown }) => LocalizedString;
  };
  alertToast: {
    /**
     * {name} a rejoint la salle
     */
    newParticipant: (arg: { name: unknown }) => LocalizedString;
    /**
     * {name} a quitté la salle
     */
    participantLeft: (arg: { name: unknown }) => LocalizedString;
    /**
     * Code copié dans le presse papier
     */
    copiedRoomCode: () => LocalizedString;
  };
  settingsPopup: {
    /**
     * Langue
     */
    language: () => LocalizedString;
  };
};

export type Formatters = {};
